parameters:
    app_vk_client.service_token: 474aacae474aacae474aacae04472e47ec4474a474aacae1c649ecbe6db860967ea9d3b
    app_vk_client.app_id: 6613826
    queue.user: vk-user-queue
    queue.album: vk-album-queue
    queue.photo: vk-photo-queue
    app.images_download_dir: '/home/vagrant/vk-photo-grabber/temp/downloads/img'
    app.db.dsn: 'mysql:dbname=vk_photo_grabber;host=localhost;'
    app.db.username: vk_photo_grabber_u
    app.db.password: qwe123

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

#    app\commands\:
#        resource: '../app/commands/*'
#        tags: [console.command]

    amqp_connection_factory:
        class: Enqueue\AmqpLib\AmqpConnectionFactory
        arguments:
            - {host: 'localhost', port: 5672, vhost: '/', user: 'admin', pass: 'qwe123'}

    Enqueue\AmqpLib\AmqpConnectionFactory: '@amqp_connection_factory'

    db:
        class: app\Db
        arguments:
            - '%app.db.dsn%'
            - '%app.db.username%'
            - '%app.db.password%'

    storage:
        class: app\Storage
        arguments:
            - '@db'

    vk_api_client:
        class: VK\Client\VKApiClient

    VK\Client\VKApiClient: '@vk_api_client'

    Interop\Queue\PsrContext:
        factory: 'Enqueue\AmqpLib\AmqpConnectionFactory:createContext'

    album_queue:
        factory: 'Interop\Queue\PsrContext:createQueue'
        arguments: ['%queue.album%']

    photo_queue:
        factory: 'Interop\Queue\PsrContext:createQueue'
        arguments: ['%queue.photo%']

    user_queue:
        factory: 'Interop\Queue\PsrContext:createQueue'
        arguments: ['%queue.user%']

    album_out_channel:
        class: app\OutChannel
        arguments:
            - '@Interop\Queue\PsrContext'
            - '@album_queue'

    photo_out_channel:
        class: app\OutChannel
        arguments:
            - '@Interop\Queue\PsrContext'
            - '@photo_queue'

    user_out_channel:
        class: app\OutChannel
        arguments:
            - '@Interop\Queue\PsrContext'
            - '@user_queue'

    user_processor:
        class: app\UserProcessor
        arguments:
            - '@app_vk_client'
            - '@album_out_channel'
            - '@storage'

    album_processor:
        class: app\AlbumProcessor
        arguments:
            - '@app_vk_client'
            - '@photo_out_channel'

    vk_image_downloader:
        class: app\VkImageDownloader
        arguments:
            - '%app.images_download_dir%'
#        class: new VkImageDownloader(__DIR__.'/../../temp/downloads/img')

    photo_processor:
        class: app\PhotoProcessor
        arguments:
            - '@vk_image_downloader'
            - '@storage'

    app_vk_client:
        class: app\VkClient
        arguments:
            $apiClient: '@vk_api_client'
            $accessToken: '%app_vk_client.service_token%'

    command_start_user_worker:
        class: app\commands\StartWorkerCommand
        arguments:
            $name: 'worker:start-user-worker'
            $psrContext: '@Interop\Queue\PsrContext'
            $processor: '@user_processor'
            $queueName: '%queue.user%'

    command_start_album_worker:
        class: app\commands\StartWorkerCommand
        arguments:
            $name: 'worker:start-album-worker'
            $psrContext: '@Interop\Queue\PsrContext'
            $processor: '@album_processor'
            $queueName: '%queue.album%'

    command_start_photo_worker:
        class: app\commands\StartWorkerCommand
        arguments:
            $name: 'worker:start-photo-worker'
            $psrContext: '@Interop\Queue\PsrContext'
            $processor: '@photo_processor'
            $queueName: '%queue.photo%'

    command_user_list:
        class: app\commands\UserListCommand
        arguments:
            $storage: '@storage'

    command_user_album_list:
        class: app\commands\AlbumListCommand
        arguments:
            $storage: '@storage'

    command_album_photo_list:
        class: app\commands\AlbumPhotoListCommand
        arguments:
            $storage: '@storage'

    command_enqueue_user:
        class: app\commands\EnqueueUserCommand
        arguments:
            $userQueue: '@user_out_channel'