---
- name: Install Supervisor
  apt:
    update_cache=yes
    name=supervisor
    state=present

- name: Create log directories
  file:
    path: /var/log/{{ vk_grabber_app_name }}
    state: directory
    owner: vagrant
    group: vagrant
    mode: 0755

- name: Install workers
  template:
    src={{ item.src }}
    dest={{ item.dest }}
    backup=yes
  with_items:
    - { src: user-worker.conf, dest: /etc/supervisor/conf.d/user-worker.conf }
    - { src: album-worker.conf, dest: /etc/supervisor/conf.d/album-worker.conf }
    - { src: photo-worker.conf, dest: /etc/supervisor/conf.d/photo-worker.conf }
  notify:
      - restart user worker
      - restart album worker
      - restart photo worker