---
- hosts: default
  vars_files:
      - vars/main.yml
      - vars/local.yml
  roles:
    - rabbitmq
    - geerlingguy.composer
    - geerlingguy.php-versions
    - geerlingguy.php
    - supervisor
  tasks:
    - name: Install packages
      apt:
        update_cache=yes
        state=present
        name={{ item }}
      with_items:
        - vim
        - htop
        - git
        - zip
