---
- hosts: default
  vars_files:
      - vars.yml
  roles:
    - rabbitmq
    - geerlingguy.composer
  tasks:
    - name: Install packages
      apt:
        update_cache=yes
        state=present
        name={{ item }}
      with_items:
        - vim
        - htop
        - php
        - git
        - zip
        - php-bcmath
        - php-mbstring
