---
- name: restart user worker
  supervisorctl:
    name="user-worker:"
    state=restarted

- name: restart album worker
  supervisorctl:
    name="album-worker:"
    state=restarted

- name: restart photo worker
  supervisorctl:
    name="photo-worker:"
    state=restarted