---
- name: Install RabbitMQ
  apt:
    update_cache=yes
    name=rabbitmq-server
    state=present

- name: Create administrator account
  rabbitmq_user:
    user: admin
    password: qwe123
    tags: administrator
    permissions:
      - vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
    state: present

- name: Enable management web UI
  rabbitmq_plugin:
    names=rabbitmq_management
    state=enabled
  notify:
    - restart rabbitmq server

- apt:
    update_cache=yes
    name=python-pip
    state=present

- pip:
    name: requests
    state: present

- name: Create user queue
  rabbitmq_queue:
    name: vk-user-queue
    durable: yes
    state: present
  ignore_errors: yes

- name: Create album queue
  rabbitmq_queue:
    name: vk-album-queue
    durable: yes
    state: present
  ignore_errors: yes

- name: Create photo queue
  rabbitmq_queue:
    name: vk-photo-queue
    durable: yes
    state: present
  ignore_errors: yes
